from .aseguradora_model import AseguradoraModel
from .chasis_marca_model import ChasisMarcaModel
from .chasis_modelo_model import ChasisModeloModel
from .existencia_stock_model import ExistenciaStockModel
from .ficha_stock_model import FichaStockModel
from .parque_movil_historial_model import ParqueMovilHistorialModel
from .parque_movil_model import ParqueMovilModel
from .repuesto_model import RepuestoModel
