from .conteo_stock_model import ConteoStockModel
from .duracion_repuestos_model import DuracionRepuestosModel
from .indice_consumo_model import IndiceConsumoModel
from .prevision_model import PrevisionModel
