SINONIMOS = {
    "REPARACION": ["REPAR."],
    "KIT REPARACION": ["KIT REP"],
    "REPARADO": ["REP", "REP.", "REPA", "REPA.", "REPARADO.", "REPARADA"],
    "NUEVO": ["NUEVA", "NVA", "NVA.", "NVO", "NVO.", "NUE", "NUE.", "NUEV.", "NUEV"],
    "CILINDRO": ["CIL", "CIL.", "CILIN.", "CILIN", "CILIND", "CILIND."],
    "DE": [" DE"],
    "ENGRANAJE": ["ENGR", "ENGR.", "ENG.", "ENG", "ENGRAN.", "ENGRAN"],
    "INYECCION": ["INY", "INY.", "INYECC", "INYECC.", "INYECTORA", "INYEC."],
    "INYECTORES": ["INYECT", "INYEC"],
    "KIT": ["JUEGO", "JGO", "JGO."],
    "KITS": ["JUEGOS"],
    "COMBUSTIBLE": ["COMB", "COMB.", "COMBUS.", "COMBUS"],
    "CIGUEÑAL": [
        "CIGUENAL",
        "CIGUE",
        "CIG",
        "CIG.",
        "CIGUEÑ",
        "CIGU",
        "CIGU.",
        "CIGUEÑ.",
    ],
    "COMPRESOR": [
        "COMPR.",
        "COMPR",
        "COMP.",
        "COMPRE",
        "COMPRE.",
        "COMP",
        "COMPRES",
        "COMPRES.",
    ],
    "AMORTIGUADORES": ["AMRTIGUADORES"],
    "CATALIZADOR": ["CATALIZ", "CATALIZ.", "CATAL", "CATAL."],
    "BARRA DIRECCION": ["BARRA DIR"],
    "BARRA DIRECCION CORTA": ["BARRA CORTA DIRECCION", "BARRA CORTA DIRECC"],
    "GOBERNADOR/SECADOR": ["GOBER. SECADOR", "GOBER/ SECADOR", "GOBERNARDOR/SECADOR"],
    "GOBERNADOR": ["GOBERNADORES"],
    "ASPIRADO": ["ASP", "ASP.", "asp.", "asp"],
    "ASPIRA": ["ASPIR.", "ASPIR"],
    "ARBOL": ["ARB.", "ARB"],
    "SECUNDARIO": ["SEC.", "SEC", "SECUND", "SECUND."],
    "MERCEDES BENZ": ["MER. BENZ", "M. BENZ", "M. B."],
    "MOTOR EVAPORADOR BITURBO": ["MOTOR EVAP BITURBO"],
    "LIMPIA": ["LIMIA"],
    "LIMPIAPARABRISAS": [
        "LIMPIAPARABRISA",
        "LP",
        "L/P",
        "L/PARABRISAS",
        "L/M",
        "LIMPIAP",
        "LIMPIA",
    ],
    "ALMA VIROLA": ["ALM VIROLA"],
    "LATERAL": ["LAT", "LAT."],
    "O'RINGS": ["O'RING", "O RING", "O/RING", "ORING", "ORINGS"],
    "KNORR": ["KNNOR", "KONRR", "KNORR."],
    "AUTOMATICO": ["AUT.", "AUTO.", "AUTOM.", "AUTAMATICO", "AUT", "AUTO", "AUTOM"],
    "EJE BURRO ARRANQUE": [
        "EJE ARRANQUE",
        "EJE COMPLETO ARRANQUE",
        "EJE DE BURRO",
    ],
    "MM": ["MM.", "mm.", "mm"],
    "GRADUAR": ["GRAD.", "GRAD"],
    "AVANCE": ["AVAN.", "AVAN"],
    "RAPIDA": ["RAP"],
    "SUMPLEMENTO": ["SUPLEM."],
    "TACHO DE BASURA": ["TACHO BASURA"],
    "NOTEBOOK": ["NOTEBEBOOK", "NOTEBOOCK"],
    "ANTEOJOS": ["ANTEOJO"],
    "ANTIPARRAS": ["ANTIPARRA"],
    "GUANTES": ["GUANTE"],
    "RESORTE": ["RESOTE"],
    "RULEMANES": ["RULEMNES"],
    "RULEMAN": [
        "RODAMIENTO",
        "RODAM",
        "RODAM.",
        "RUL",
        "RULEM",
        "RULEM.",
        "RUL.",
        "ROD.",
    ],
    "SUBCONJUNTO": ["SUBCONJ", "SUBCONJ."],
    "BUJE ALTERNADOR": ["BUJE PARA ALTERNADOR"],
    "PICO DE ENGRASE": ["PICO ENGRASE"],
    "PISTOLA DE ENGRASE": ["PISTOLA ENGRASE"],
    "THINNER": ["THINER"],
    "COLUMNA DE DIRECCION": ["COLUMNA DIRECCION"],
    "CRUCETA": ["CRUZETA", "CRUZ."],
    "CONEXION": ["CONEX", "CONEX."],
    "ARANDELA": ["ARNDELA", "ARAND.", "ARAND"],
    "VIDRIO": ["VIDRO", "VID"],
    "PANEL LED": ["PANEL LUCES", "PANEL DE LUCES"],
    "LISTON LED": ["LISTON DE LED"],
    "LLAVES": ["LLAVE"],
    "KIT REFORMA": ["KIT REF"],
    "T": ["¿T"],
    "TORX (TIPO ALLEN)": ["TORX(TIPO ALLEN)"],
    "MANTENIMIENTO": ["MANTEMIENTO"],
    "JUNTAS": ["JTAS", "JUNTA"],
    "BANANA MT17 EURO V MERITOR DER REPARADA": [
        "BANANA MT17 EURO V MERITOR DER REPARADO"
    ],
    "KIT DE": ["SET DE"],
    "KIT DETECTOR": ["KIT DETECCION"],
    "KIT EMBRAGUES": ["KIT EMBRAG"],
    "BOCALLAVES": ["BOCALAVES"],
    "HERRAMIENTAS": ["HERRAMENTAS", "HERRAM.", "HERRAMIENTA"],
    "ROTOMARTILLO": ["ROTO MARTILLO"],
    "POSTRATAMIENTO": ["POST TRATAMIENTO"],
    "METALPAR": ["MTALPAR", "METAL."],
    "CHICOTE": ["CHCOTE"],
    "ESTIRA CORREA": ["EST'RREA"],
    "REPARACION (ENGRASE Y CORREAS)": ["REPAR(ENGR Y CORREAS)"],
    "PIÑON BURRO ARRANQUE": ["PIÑON ARRANQUE"],
    "PLANETARIO BURRO ARRANQUE": ["PLANET ARRANQUE"],
    "SOLENOIDE": ["SELENOIDE"],
    "BURRO ARRANQUE": ["ARRAN"],
    "PARA FLEXIBLE": ["P'/FLEXIBLE"],
    "ACRILICO TRASERO": ["ACRILICO TRANS", "ACRILICO TRAS"],
    "INFERIOR": ["INFE", "INFE.", "INF", "INF."],
    "CANALIZADOR": ["CANAL.", "CANAL", "CANALIZ", "CANALIZ."],
    "CORRUGADO": ["CORRUG", "CORRUG."],
    "SUPERIOR": ["SUP", "SUP."],
    "SUPERIOR/INFERIOR": ["SUP/INF.", "SUP./INF.", "SUP/INF"],
    "ADAPTADOR": ["ADPTADOR", "ADAP/"],
    "ELEVA": ["ELEV."],
    "TANQUE DE AGUA": ["T. DE AGUA", "T. AGUA"],
    "ADICIONAL": ["ADIC.", "ADIC"],
    "DIFERENCIAL": ["DIF", "DIF."],
    "ESTABILIZADORA": ["ESTAB", "ESTAB.", "EST", "EST."],
    "ABRAZADERA": ["ABRAZ.", "ABRAZ", "ABRADERA"],
    "SALIDA": ["SALI", "SAL", "SAL.", "SALI."],
    "DISCO": ["DIS.", "DIS"],
    "(BAM": ["(BAM."],
    "GEN": ["GEN."],
    "EATON": ["EATON."],
    "ENDURECEDOR": ["END", "END."],
    "PASO FINO": ["P. FINO"],
    "PROGRAMACION": ["PROG."],
    "INTERCOOLER": ["INTER", "INTER."],
    "RADIADOR": ["RAD.", "RAD", "RADIAD.", "RADIAD"],
    "SILENCIADOR": ["SILENC"],
    "POLEA CIGUEÑAL": ["POLEA DE CIGUEÑAL"],
    "PRESION": ["PRES", "PRES."],
    "N°": ["N°:", "N", "N:"],
    "VALVULA": ["VALV.", "VALV", "VALVULITA", "VAL", "VAL."],
    "EMBOLO": ["EMB."],
    "LADO DERECHO": ["L-DER"],
    "LADO IZQUIERDO": ["L-IZQ"],
    "CAMARA": ["CAMARAS", "CAM.", "CAM"],
    "CARROCERIA": ["CARROC.", "CARROC"],
    "PEDAL": ["PEDAL."],
    "HEMBRA": ["HEMRA", "HEM.", "HEM", "HEMB", "HEMB."],
    "TEMPERATURA": ["TEMP", "TEMP."],
    "BUJES BURRO ARRANQUE": ["BUJES ARRANQUE", "BUJE ARRANQUE"],
    "AUTOMATICO BURRO ARRANQUE": ["AUTOMATICO ARRANQUE"],
    "TROMPA BURRO ARRANQUE": ["TROMPA ARRANQUE"],
    "BOBINA BURRO ARRANQUE": ["BOBINA ARRANQUE"],
    "BULON BURRO ARRANQUE": ["BULON BURRO", "BULON MOTOR ARRANQUE"],
    "CORONA BURRO ARRANQUE": ["CORONA ARRANQUE", "CORONA DE ARRANQUE"],
    "PISTON BURRO ARRANQUE": ["PISTON ARRANQUE"],
    "RELAY BURRO ARRANQUE": ["RELAY ARRANQUE"],
    "BENDIX BURRO ARRANQUE": ["BENDIX ARRANQUE"],
    "PORTACARBONES BURRO ARRANQUE": ["PORTACARBONES ARRANQUE"],
    "TAPA BURRO ARRANQUE": ["TAPA ARRANQUE"],
    "TAPA CON CARBONES BURRO ARRANQUE": ["TAPA CON CARBONES ARRANQUE"],
    "KIT SEGURO BURRO ARRANQUE": ["KIT SEGURO ARRANQUE"],
    "SEGURO BENDIX BURRO ARRANQUE": ["SEGURO BENDIX ARRANQUE"],
    "IMPULSOR BURRO ARRANQUE": ["IMPULSOR DE ARRANQUE"],
    "CONTACTOR BURRO ARRANQUE": ["CONTACTOR DE ARRANQUE"],
    "LIJADORA": ["LJADORA"],
    "FIJACION": ["FIJAC", "FIJAC."],
    "ELASTICO": ["ELASTICOS"],
    "REGULADOR": ["REG.", "REG", "REGUL", "REGUL."],
    "JUNTA": ["JTA", "JTA."],
    "SINCRONIZADO": ["SINCRONIZ"],
    "ANTENA GPS": ["ANTENA GPRS"],
    "CALIBRA": ["CAL."],
    "ARANDELA COBRE": ["ARANDELA COBREN"],
    "(GOLILLA) INYECTOR": ["(GOLILLA)INYECT"],
    "ESPACIADORA": ["ESPACI"],
    "ENTRE POLEA": ["E/POLEA"],
    "SOBREPOLEA": ["SOBREPOL.", "SOBREPOL"],
    "HEXAGONAL": ["HEXAG.", "HEXAG", "HEX.", "HEX", "HEXA"],
    "FUSIBLERA": ["FUSILERA"],
    "VELOCIDAD": ["VELOC.", "VELOC"],
    "PUNTA": ["PTA"],
    "NACIONAL": ["NAC", "NAC.", "NACIO", "NACI", "NACIO.", "NACI."],
    "ORIGINAL": [
        "ORIGI",
        "ORI",
        "ORIGIN",
        "ORI.",
        "ORIGIN.",
        "ORIGI.",
        "ORIG",
        "ORIG.",
    ],
    "OFICIAL": ["OFC.", "OFC"],
    "CALISUAR": ["CALISUA"],
    "VULCANIZADO": ["VULC."],
    "DESINFECCION": ["DESINFECC.", "DESINFECC", "DESINFECCION."],
    "CUADRADO": ["CUAD", "CUAD."],
    "PORTAPLANETA": ["PORTAPLANET.", "PORTA PLANETA", "PORTAPLANET"],
    "BARRA TRASERA": ["BARRA TRAS"],
    "BUJE CABEZAL": ["BUJE CABEZA"],
    "REFORZADO": ["REFOR", "REF.", "REFOR.", "REF"],
    "REFRIGERACION": ["REFRIG", "REFRIG.", "REFRIGE", "REFRIGE."],
    "SELECTIVA": ["SELECTICA"],
    "DELANTERA/TRASERA": ["DEL./TRAS.", "DEL./TRAS", "DEL/TRAS.", "DEL/TRAS"],
    "PARAGOLPES": ["PARAGOL.", "PARAGOLPE", "PARAGOL"],
    "CUMMINS": ["CUMM", "CUMM.", "CUMMMINS"],
    "6 CIL": [
        "6C",
        "6C.",
        "6 CIL.",
        "6CIL",
        "6CIL.",
        "6 CI",
        "6C:",
        "6 CILINDROS",
        "6 CILINDRO",
    ],
    "5 CIL": [
        "5C",
        "5C.",
        "5 CIL.",
        "5CIL",
        "5CIL.",
        "5 CI",
        "5C:",
        "5 CILINDROS",
        "5 CILINDRO",
    ],
    "4 CIL": [
        "4C",
        "4C.",
        "4 CIL.",
        "4CIL",
        "4CIL.",
        "4 CI",
        "4C:",
        "4 CILINDROS",
        "4 CILINDRO",
    ],
    "12 MM REFERENCIA": ["12MMREF."],
    "PERFORADOR": ["PERFO.", "PERFO"],
    "SEGURIDAD": ["SEGURID"],
    "ELECTRICO": ["ELCTRICO"],
    "CIGUEÑAL / ARBOL DE LEVAS": ["CIGUEÑ/ARB"],
    "TERCERA": ["TERC."],
    "ETAPA": ["ETAP."],
    "MAXXFORCE": ["MAXFORCE"],
    "MOTOR EVAPORADOR BITURBO CALEFACCION": ["BITURBO CALEFACCION"],
    "FLEXIBLE MOTOR": ["A F. MOTOR", "F. MOTOR"],
    "POLIURETANO PARA RETOQUE": ["POL P/RETOQUE"],
    "ACOPLAMIENTO": ["ACOPLAM"],
    "12MM REFORZADA": ["12MM REF."],
    "12MM": ["12MM."],
    "AUTOMATICO BURRO ARRANQUE AGRALE": ["AUTOMATICO DE BURRO DE ARRANQUE AGRALE"],
    "CORTA CURVA": ["CORTA/CURVA"],
    "ENFRIADORA": ["ENFIADORA"],
    "ENFRIADOR": ["ENF.", "ENF"],
    "ESTIRACORREA": ["ESTIRA CORREA", "ESTIRACORR", "EST'REA"],
    "PASAMANOS": ["PASAMANO"],
    "CUMMINS 4 CIL": [
        "CUMM4",
        "CUMM4.",
        "CUMM.4C",
        "CUMM.4C.",
        "CUMM4C.",
        "CUMM4C",
        "CUMNS 4 CIL",
        "CUM4C",
    ],
    "CUMMINS 6 CIL": [
        "CUMM6",
        "CUMM.6C",
        "CUMM.6C.",
        "CUMM6C.",
        "CUMM6C",
        "CUMNS 6 CIL",
        "CUM6C",
    ],
    "MECHA": ["MCHA"],
    "MAGNETICO": ["MGNETICO"],
    "RULEMAN COLUMNA": ["RODAMCOLUMA"],
    "VENTILADOR": ["VENT.", "VEMT", "VENT", "VENTIL."],
    "BASE TRASERA": ["BASE TRAS"],
    "ESTIRATURBINA": ["ESTIRA. TURBINA"],
    "45AH": ["4. 5AH"],
    "CHICA": ["CHI", "CHI."],
    "GRANDE": ["GDE", "GDE."],
    "ANTERIOR": ["ANTE.", "ANTE", "ANT", "ANT."],
    "DEUTZ": ["DEUTS", "DEUZ", "DEU", "DEUT.", "DEUT", "Deutz"],
    "DEUTZ (TODOS)": ["DEUTZ(TODOS)", "DEUTZ(TOD"],
    "DELANTERA": ["DELAN", "DELAN.", "DEL", "DEL.", "DELANT.", "DELANT"],
    "TRASERA": ["TRAS", "TRAS.", "TRA", "TRA."],
    "ECOLOGICO": ["ECOL", "ECOL."],
    "SELECTORA": ["SEL."],
    "ELECTROVALVULA": ["ELECTROV", "ELE'VULA"],
    "ENCASTRE": ["ENC", "ENC."],
    "ALTO IMPACTO": ["A/IMPACTO", "ALTO IMPAC", "A/MPACTO"],
    "LARGO ALTO IMPACTO": ["LARGO/ALTO IMPACT"],
    "BOOGUIE": ["BOGGUIE", "BOOGIE", "BOOGUI", "BUGGI"],
    "DIRECCION": ["DIR", "DIR.", "DIRECION", "DIRECC"],
    "HIDRAULICA": ["HID", "HID."],
    "ROTATIVO": ["ROTATIIVO"],
    "ADMISION/ESCAPE": ["ADM/ESC.", "ADM/ESC", "ADM./ESC", "ADM./ESC."],
    "ESCAPE": ["ESCP", "ESCP.", "ESC", "ESC.", "ESCAP", "ESCAP.", "ESCA.", "ESCA"],
    "UNIDADES": ["UNI", "UNI.", "UNID", "UNID."],
    "SURTIDOR": ["SURT"],
    "MWM 4C": ["MM4C", "MM4C."],
    "AMORTIGUADOR": ["AMRTIGUADOR", "AMORT", "AMORT."],
    "A/A": ["A/C", "A/AC."],
    "BORDEADORA/DESMALEZADORA": ["BORDEADORA /DESMALEZADORA"],
    "SALIDA DE AGUA": ["SAL/AGUA"],
    "SUSPENSION ORIGINAL": ["SUSP.ORIGINAL"],
    "SUSPENSION": ["SUSP", "SUSP.", "SUSPEN", "SUSPEN."],
    "PARABALLENKER": ["PARABALENKE", "PARABALENQUE"],
    "SOPORTE POLEA": ["SOP/POLEA"],
    "PRESION Y TEMPERATURA": ["PRESION/TEMPERATURA"],
    "ALLEN": ["ALLEM"],
    "BANCADA": ["BANCADA.", "BANCAD.", "BANCAD", "BANC", "BANC."],
    "SOPORTE": ["SOP.", "SOP"],
    "FLEXIBLE": ["FLEXI", "FLEXI.", "FLEX.", "FLEX", "CONT. FLEXIBLE"],
    "CAPUCHON": ["CAPUCH'N"],
    "CUBREVOLANTE": ["CUBREV.", "CUBREV", "CUBRE VOLANTE"],
    "VOLANTE": ["VOL.", "VOL", "VOLAN", "VOLAN."],
    "DISTRIBUCION": [
        "DIST",
        "DIST.",
        "DISTR",
        "DISTR.",
        "DEISTR.",
        "DISTRI.",
        "DISTRI",
        "DISTRIB",
        "DISTRIB.",
        "DITRIBUCION",
    ],
    "DERECHA": ["DER.", "DER", "DERECHO"],
    "IZQUIERDA": ["IZQ.", "IZQ", "IZQUIERDO"],
    "TERMINAL": ["TERM", "TERM."],
    "POSTERIOR/ENFRIADOR": ["POST/ENF."],
    "EMBRAGUE": ["EMBRAGE", "EMBRIAGUE", "EMBRIAGE"],
    "CASQUILLO": ["CASQUILO"],
    "CPU": ["CEREBRO ELECTRONICO", "COMPUT.", "COMPUTADORA"],
    "RESPIRADERO": ["RESP.", "RESP", "RESPI.", "RESPI"],
    "CUERPO": ["CPO", "CPO."],
    "EXTERIOR": ["EXT", "EXT."],
    "INTERIOR": ["INT", "INT."],
    "CON Y SIN": ["C/S"],
    "SALIDA Y ENTRADA": ["SAL/ENT"],
    "DISPOSITIVO ROTATIVO": ["DISP. ROTAC."],
    "1°": ["1ER", "1ERA", "1A.", "1RA", "1RA."],
    "2°": ["2DO", "2DA", "2A.", "2DA."],
    "3°": ["3RO", "3ERO", "3RA", "3ERA"],
    "4°": ["4TO", "4TA"],
    "5°": ["5TO", "5TA"],
    "6°": ["6TO", "6TA", "6TS"],
    "ACCION": ["ACC"],
    "ACCESORIO": ["ACC."],
    "ARBOL DE LEVAS": ["ARBOL LEVA"],
    "DIRECCION HIDRAULICA": ["D. H.", "D. H"],
    "INTERMEDIO": ["INTERM."],
    "GENERAL": ["GRAL", "GRAL."],
    "PLANETARIO": ["PLANET", "PLANET."],
    "RECAMBIO": ["RECAM.", "RECAM"],
    "BOMBA DE AGUA": ["BBA. AGUA"],
    "DESLIZANTE": ["DESLIZ", "DESLIZ."],
    "CALEFACCION": [
        "CALEFAC",
        "CALEFAC.",
        "CALEFACC",
        "CALEFACC.",
        "CALEFA",
        "CALEFA.",
        "CALEF",
        "CALEF.",
        "CALEFC.",
    ],
    "BALANCIN": ["BALANC", "BALANC.", "BALAN.", "BALAN"],
    "PUNTO": ["PTO", "PTO."],
    "ESPARRAGO CONO TUERCA": ["ESPARRAGO-CONO-TUERCA"],
    "MULTIPLE": ["MULTI.", "MULT", "MULT."],
    "ADMISION": ["ADMIS.", "ADM.", "ADM"],
    "EXCENTRICO": ["EXCENTRICOS"],
    "CUMMINS 4 Y 6 CIL": ["CUMM4C/6C"],
    "CAJA AUTOMATICA": [
        "CAJA AUT.",
        "CAJA AUTOMATICO",
        "CAJA AUTOM",
        "CAJA AUTOM.",
        "CAJA AUT",
        "CAJ.",
    ],
    "RETARDER": ["RETARDADOR", "RETARD.", "RETARD", "RETARDO"],
    "PULMON FRENO": ["P. FRENO"],
    "PULMON": ["PULMN"],
    "TEFLON POLIAMIDA": ["TEFLON/POLIA"],
    "SWITCH": ["SWICH"],
    "GANCHO": ["GANCHOS"],
    "GEMELO": ["GEMELOS"],
    "INCORPORADO": ["INCORP", "INCORP."],
    "PARA RULEMANES": ["PARA RUL"],
    "HELICOIL": ["HELICOIL.", "HILICOIL."],
    "LIQUIDO": ["L."],
    "RECTIFICAR": ["RECTIF."],
    "TALLER": ["TALL."],
    "ELECTRICA": ["ELECTR.", "ELEC/", "ELECT", "ELECTR", "ELECT.", "ELEC."],
    "INSTALACION": ["INST.", "INSTAL."],
    "INYECTORES BULBOS": ["INYEC/BULBOS"],
    "TURBO": ["TUR"],
    "COMPLETA": ["COMPL", "COMPL."],
    "LAMPARA LED": ["LAMPARA LEDS"],
    "ZOCALO TECLA ELOD DE 5 UNIDADES": ["Zocalo Tecla Elod de 5 Unidades"],
    "MB": ["MB."],
    "MB O500": ["MB 0500"],
    "CHOFER": ["CHOF"],
    "VIDRIO PUERTA": ["VIDRIO P"],
    "APERTURA": ["AP", "ABERTURA", "APERT"],
    "AIRES": ["ARIES"],
    "VASTAGO": ["VASTAGOS"],
    "PARA SENSOR": ["P/SENSOR"],
    "HORQUILLA": ["HORQ", "HORQ."],
    "ACELERADOR": ["ACEL", "ACEL."],
    "SOBREPRESION": ["SOBRE PRESION", "SOB/PRES"],
    "ACEITE": ["ACEI", "AC."],
    "PURGADOR": ["PURGUE"],
    "NEUMATICO": ["NUEMATICO"],
    "LUBRICANTE": ["LUBR", "LUBR.", "LUBRIC", "LUBRIC."],
    "EXPANSION": ["EXPANSORA", "EXPANSON", "EXPANCION"],
    "TANQUE": ["TANQ"],
    "ESTACION DE SERVICIO": ["EST. SRV", "EST SRV.", "EST. SRV.", "EST SRV"],
    "DESAGOTE": ["DESAG"],
    "DESCARGA": ["DESC", "DESC.", "DESCAR", "DESCAR."],
    "VENTANA": ["VEN", "VENTANILLA", "VENTANILL A", "VENTANA"],
    "MASCARA": ["MASC", "MASC."],
    '"T"': ["T"],
    "MANGUERA AGUA": ["MANG/AGUA"],
    "MANGUERA": ["MANG", "MANG.", "MNGUERA", "MNG"],
    "SALIDA DE CAJA": ["SAL/CAJA"],
    "TRANSMISION": ["TRANSMSION"],
    "CAÑONERA": ["CAÑON."],
    "ACANALADO": ["ACAN."],
    "POSTERIOR": ["POSTER.", "POSTER", "POST", "POST.", "POSTE.", "POSTE"],
    "PORTACORONA": ["PORTACOR.", "PORTA CORONA"],
    "PORTATAPON": ["PORTA TAPON"],
    "ALTERNADOR": ["ALTER/", "ALTER", "ALTER.", "ALT", "ALT."],
    "AGUJA": ["AGUJ"],
    "TENSOR/CORREDERA": ["TENSOR/CORRED."],
    "AUXILIOS": ["AUX."],
    "A": ["A."],
    "B": ["B."],
    "C": ["C."],
    "SOLDADOR": ["SOLD."],
    "MARCOPOLO": ["M. POLO", "MARCO POLO"],
    "CON O SIN NEUTRO": ["C/S/NEUTRO"],
    "T270": ["T-270", "T 270"],
    "CONVERTIDOR": [
        "COMV",
        "CONV.",
        "CONV",
        "CONVERTI",
        "CONVERTI.",
        "CONVERT.",
        "CONVERT",
    ],
    "TCM T270": ["TCMT270"],
    "MAQUINA (LF670 B95)": ["MAQ.( LF670 B95)"],
    "UNIDAD SELLADA": ["U. SELLA."],
    "FLEETGUARD": ["FLEET.", "FLEET", "FLEETGU", "FLEETGU."],
    "VELOCIMETRO": ["VELOCIM", "VELOCIM."],
    "TODOBUS": ["T. BUS", "TB", "T. B", "T B.", "T B", "TODO BUS", "T. B."],
    "TOYOTA": ["TOY", "TOY."],
    "ESTANDAR": ["STD", "STD."],
    "OH/CARROCERIA": ["OH/CARROC."],
    "ELEVADOR": ["ELEVA"],
    "PLASTICO": ["PLASTIC", "PLASTIC.", "PLAST.", "PLAST"],
    "ELASTICA": ["ELAST.", "ELAST"],
    "CAPAS RECTO": ["C. RECTO"],
    "CAPAS AMERICANO": ["C. AMERICANO"],
    "OH": ["OH."],
    "USO": ["USO."],
    "USAR": ["USAR."],
    "COMPRESOR DE AIRE": ["C. A."],
    "AJUSTE": ["AJUST."],
    "THERMOKING": ["TK.", "TK", "T. KING", "THERMO K.", "T.K.", "T. K.", "T. K"],
    "ESPECIAL": ["ESP."],
    "TERMOSTATO/RADIADOR": ["TERM./RAD."],
    "UREA/REFRIGERANTE": ["UREA/REF."],
    "TURBINA": ["TURBI", "TURBI."],
    "ESTROBOSCOPICA": ["ESTROB."],
    "": ["INTE."],
}
